cgview:
  ruler:
    font: 'sans-serif, plain, 10'
    fontColor: 'black'
  backbone:
    color: 'grey'
    thickness: 5
  dividers:
    slot:
      show: true
      thickness: 1
      color: 'black'
  sequence:
    font: 'sans-serif, plain, 14'
    color: 'black'
  featureTypes:
    - name: 'CDS'
      decoration: 'arrow'
    - name: 'tRNA'
      decoration: 'arrow'
    - name: 'rRNA'
      decoration: 'arrow'
    - name: 'blast'
      decoration: 'arc'
    - name: 'codon'
      decoration: 'arc'
    - name: 'DEFAULT'
      decoration: 'arrow'
  captions:
    - name: "Title"
      position: "bottom-center"
      fontColor: "orange"
      backgroundColor: "rgba(255,255,255,0.4)"
      font: "sans-serif, plain, 24"
    # - name: "More info"
    #   position: "top-left"
    #   fontColor: "red"
    #   backgroundColor: "rgba(255,255,255,0.4)"
    #   font: "sans-serif, plain, 14"
    #   items:
    #     - name: 'Accession: 123456'
    #     - name: 'Length: Short'
  legend:
    position: 'top-right'
    alignment: 'left'
    fontColor: 'black'
    backgroundColor: 'rgba(255,255,255,0.75)'
    font: 'sans-serif, plain, 14'
    default: 'Other'
    items:
      - name: 'CDS'
        swatchColor: 'rgba(0,0,153,0.5)'
        decoration: 'arrow'
      - name: 'tRNA'
        swatchColor: 'rgba(153,0,153,0.5)'
      - name: 'rRNA'
        swatchColor: 'rgba(0,153,53,0.5)'
      - name: 'Other'
        swatchColor: 'rgba(153,153,153,0.5)'
  tracks:
      # - name: 'Start/Stop Codons'
      #   readingFrame: 'separated'
      #   position: 'both'
      #   contents:
      #     type: 'feature'
      #     from: 'sequence'
      #     extract: 'start-stop-codons'
      # - name: 'ORFs'
      #   readingFrame: 'separated'
      #   position: 'both'
      #   contents:
      #     type: 'feature'
      #     from: 'sequence'
      #     extract: 'orfs'
      # - name: 'CG Content'
      #   position: 'inside'
      #   contents:
      #     type: 'plot'
      #     from: 'sequence'
      #     extract: 'gc-content'
      # - name: 'CG Skew'
      #   position: 'inside'
      #   contents:
      #     type: 'plot'
      #     from: 'sequence'
      #     extract: 'gc-skew'



